FROM openjdk:8

WORKDIR /usrapp/bin

ENV PORT 35000

COPY /target/classes/co/edu/escuelaing/Log.class /usrapp/bin/classes/co/edu/escuelaing/
COPY /target/classes/co/edu/escuelaing/LogService.class /usrapp/bin/classes/co/edu/escuelaing/
COPY /target/classes/co/edu/escuelaing/MongoUtil.class /usrapp/bin/classes/co/edu/escuelaing/

COPY /target/dependency /usrapp/bin/dependency

CMD ["java","-cp","./classes:./dependency/*","co.edu.escuelaing.LogService"]