FROM openjdk:8

WORKDIR /usrapp/bin

ENV PORT 46000

COPY /target/classes/co/edu/escuelaing/LogServerFacade.class /usrapp/bin/classes/co/edu/escuelaing/
COPY /target/classes/co/edu/escuelaing/RemoteLogServiceInvoker.class /usrapp/bin/classes/co/edu/escuelaing/
COPY /target/classes/public /usrapp/bin/classes/public

COPY /target/dependency /usrapp/bin/dependency

CMD ["java","-cp","./classes:./dependency/*","co.edu.escuelaing.LogServerFacade"]